services:
  n8n:
    image: n8nio/n8n:2.3.5
    container_name: n8n
    restart: unless-stopped
    ports:
      - 5678:5678
    environment:
      - N8N_HOST=n8n.mightbesimon.com
      - WEBHOOK_TUNNEL_URL=https://n8n.mightbesimon.com/
      - WEBHOOK_URL=https://n8n.mightbesimon.com/
      - GENERIC_TIMEZONE=Europe/Paris
      - TZ=Europe/Paris
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=false
      - N8N_PYTHON_BINARY=/usr/bin/python3
      - N8N_METRICS=true
      - QUEUE_HEALTH_CHECK_ACTIVE=true
    volumes:
      - n8n_volume:/home/node/.n8n
    networks:
      - n8n_network

volumes:
  n8n_volume:
    driver: local

networks:
  n8n_network:
    driver: bridge
